export const sagaActions = {
    DO_LOGIN_SAGA: 'DO_LOGIN',
    DO_LOGOUT_SAGA: 'DO_LOGOUT',
    DO_REGISTRATION_SAGA: 'DO_REGISTRATION',
    FETCH_EMPLOYEE_SAGA: 'FETCH_EMPLOYEE',
    ADD_EMPLOYEE_SAGA: 'ADD_EMPLOYEE',
    UPDATE_EMPLOYEE_SAGA: 'UPDATE_EMPLOYEE',
    DELETE_EMPLOYEE_SAGA: 'DELETE_EMPLOY',
  }